/*
 * dialog1.java
 *
 * Created on 20 ќкт€брь 2000 г., 23:08
 */
 
package qqq;
import java.awt.*;
import javax.swing.*;
import java.lang.*;
import java.awt.event.*;
/** 
 *
 * @author  unknown
 * @version 
 */
public class dialog1 extends javax.swing.JDialog {
  private String typedText = null;
  public  String getValidatedText(){
    return typedText;
  }
  final String msgString1 = "This string will be added to a new window";
  private JTextField textField;
  private Object[] array  = {msgString1, textField};
  final String btnString1 = "Enter";
  final String btnString2 = "Cancel";
  Object[] options = {btnString1, btnString2};

  
  /** Creates new form dialog1 */
  public dialog1(JFrame parent,String title,boolean modal) {
    super (parent, modal);
    textField = new JTextField(title,10);
    array[1] = textField;
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    jOptionPane1 = new javax.swing.JOptionPane ();
    setModal (true);
    setForeground (java.awt.Color.orange);
    setBackground (java.awt.Color.white);
    setDefaultCloseOperation (javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        switch_to_optionPane (evt);
      }
    }
    );

    jOptionPane1.setLayout (new java.awt.FlowLayout ());
    jOptionPane1.setOptionType (javax.swing.JOptionPane.YES_NO_OPTION);
    jOptionPane1.setMessage (array);
    textField.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jOptionPane1.setValue(btnString1);
      }
    });

    jOptionPane1.setOptions (options);
    jOptionPane1.setInitialValue (options[0]);
    jOptionPane1.addPropertyChangeListener (new java.beans.PropertyChangeListener () {
      public void propertyChange (java.beans.PropertyChangeEvent evt) {
        checkTheAnswer (evt);
      }
    }
    );


    getContentPane ().add (jOptionPane1, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

private void checkTheAnswer (java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkTheAnswer
// Add your handling code here:
  String prop = evt.getPropertyName();
   if (isVisible() && (evt.getSource() == jOptionPane1)
                   && (prop.equals(JOptionPane.VALUE_PROPERTY) ||
                       prop.equals(JOptionPane.INPUT_VALUE_PROPERTY))) {
      Object value = jOptionPane1.getValue();
      if (value == JOptionPane.UNINITIALIZED_VALUE) {
       //ignore reset
        return;
      }

      // Reset the JOptionPane's value.
      // If you don't do this, then if the user
      // presses the same button next time, no
      // property change event will be fired.
      jOptionPane1.setValue(JOptionPane.UNINITIALIZED_VALUE);

      if (value.equals(btnString1)){ 
           typedText = textField.getText();
          // we're done; dismiss the dialog
      }else {
           if (!value.equals(btnString2)) // user  closed the window
                typedText = null;
       }   
      setVisible(false);
   
    }      
  }//GEN-LAST:event_checkTheAnswer

private void switch_to_optionPane (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_switch_to_optionPane
// Add your handling code here:
   jOptionPane1.setValue(new Integer(JOptionPane.CLOSED_OPTION));

  }//GEN-LAST:event_switch_to_optionPane
 
  /** Closes the dialog */
 

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JOptionPane jOptionPane1;
  // End of variables declaration//GEN-END:variables

}