
/*
 * jFrame1.java
 *
 * Created on 7 ќкт€брь 2000 г., 0:40
 */
 
package qqq;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import qqq.dialog1;
import qqq.myFrame;
/** 
 *
 * @author  Nastia
 * @version 
 */
public class jFrame1 extends myFrame {

  /** Creates new form jFrame1 */
  public jFrame1() {
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        exitForm (evt);
      }
    }
    );

  }//GEN-END:initComponents




  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm

  

}