/* h2d_vga.h  Feb 18  12:3:29  1999 */
/* Generated by H2D v1.31.1 */
/* from module h2d_vga and header vga.h. */
/* Types which were created during translation */

#include <svgalib/vga.h>

#ifndef h2d_vga_H_
#define h2d_vga_H_



#ifndef _H2D_TYPE_PaletteVector
# define _H2D_TYPE_PaletteVector
  typedef signed int * PaletteVector;
#endif  /* _H2D_TYPE_PaletteVector */

#ifndef _H2D_TYPE_String
# define _H2D_TYPE_String
  typedef signed char * String;
#endif  /* _H2D_TYPE_String */

#ifndef _H2D_TYPE_SetAperturePage
# define _H2D_TYPE_SetAperturePage
  typedef void( * SetAperturePage)( signed int page );
#endif  /* _H2D_TYPE_SetAperturePage */

#ifndef _H2D_TYPE_vga_modeinfo_ptr
# define _H2D_TYPE_vga_modeinfo_ptr
  typedef vga_modeinfo * vga_modeinfo_ptr;
#endif  /* _H2D_TYPE_vga_modeinfo */

#ifndef _H2D_TYPE_ShutdownRoutine
# define _H2D_TYPE_ShutdownRoutine
  typedef void( * ShutdownRoutine)( );
#endif  /* _H2D_TYPE_ShutdownRoutine */

#endif  /* h2d_vga_H_ */