/* h2d_vgagl.h  Feb 18  12:3:29  1999 */
/* Generated by H2D v1.31.1 */
/* from module h2d_vgagl and header vgagl.h. */
/* Types which were created during translation */

#include <svgalib/vgagl.h>

#ifndef h2d_vgagl_H_
#define h2d_vgagl_H_

#ifndef _H2D_TYPE_SetPixelFunc
# define _H2D_TYPE_SetPixelFunc
  typedef void( * SetPixelFunc)( int, int, int );
#endif  /* _H2D_TYPE_SetPixelFunc */

#ifndef _H2D_TYPE_GetPixelFunc
# define _H2D_TYPE_GetPixelFunc
  typedef int( * GetPixelFunc)( int, int );
#endif  /* _H2D_TYPE_GetPixelFunc */

#ifndef _H2D_TYPE_HLineFunc
# define _H2D_TYPE_HLineFunc
  typedef void( * HLineFunc)( int, int, int, int );
#endif  /* _H2D_TYPE_HLineFunc */

#ifndef _H2D_TYPE_FillBoxFunc
# define _H2D_TYPE_FillBoxFunc
  typedef void( * FillBoxFunc)( int, int, int, int, int );
#endif  /* _H2D_TYPE_FillBoxFunc */

#ifndef _H2D_TYPE_PutBoxFunc
# define _H2D_TYPE_PutBoxFunc
  typedef void( * PutBoxFunc)( int, int, int, int, void *, int );
#endif  /* _H2D_TYPE_PutBoxFunc */

#ifndef _H2D_TYPE_GetBoxFunc
# define _H2D_TYPE_GetBoxFunc
  typedef void( * GetBoxFunc)( int, int, int, int, void *, int );
#endif  /* _H2D_TYPE_GetBoxFunc */

#ifndef _H2D_TYPE_PutBoxMaskFunc
# define _H2D_TYPE_PutBoxMaskFunc
  typedef void( * PutBoxMaskFunc)( int, int, int, int, void * );
#endif  /* _H2D_TYPE_PutBoxMaskFunc */

#ifndef _H2D_TYPE_PutBoxPartFunc
# define _H2D_TYPE_PutBoxPartFunc
  typedef void( * PutBoxPartFunc)( int, int, int, int, int, int, void *, int, int );
#endif  /* _H2D_TYPE_PutBoxPartFunc */

#ifndef _H2D_TYPE_GetBoxPartFunc
# define _H2D_TYPE_GetBoxPartFunc
  typedef void( * GetBoxPartFunc)( int, int, int, int, int, int, void *, int, int );
#endif  /* _H2D_TYPE_GetBoxPartFunc */

#ifndef _H2D_TYPE_CopyBoxFunc
# define _H2D_TYPE_CopyBoxFunc
  typedef void( * CopyBoxFunc)( int, int, int, int, int, int );
#endif  /* _H2D_TYPE_CopyBoxFunc */

#ifndef _H2D_TYPE_GraphicsContextPtr
# define _H2D_TYPE_GraphicsContextPtr
  typedef GraphicsContext * GraphicsContextPtr;
#endif  /* _H2D_TYPE_GraphicsContextPtr */

#ifndef _H2D_TYPE_Color
#define _H2D_TYPE_Color

typedef struct {
          unsigned char red;
          unsigned char green;
          unsigned char blue;
        } Color;
#endif  /* _H2D_TYPE_Color */

#endif  /* h2d_vgagl_H_ */