/* h2d_vgajoystick.h  Feb 18  12:3:31  1999 */
/* Generated by H2D v1.31.1 */
/* from module h2d_vgajoystick and header vgajoystick.h. */
/* Types which were created during translation */

#include <svgalib/vgajoystick.h>

#ifndef h2d_vgajoystick_H_
#define h2d_vgajoystick_H_

#endif  /* h2d_vgajoystick_H_ */