/* h2d_vgakeyboard.h  Feb 18  12:3:31  1999 */
/* Generated by H2D v1.31.1 */
/* from module h2d_vgakeyboard and header vgakeyboard.h. */
/* Types which were created during translation */

#include <svgalib/vgakeyboard.h>

#ifndef h2d_vgakeyboard_H_
#define h2d_vgakeyboard_H_

#endif  /* h2d_vgakeyboard_H_ */