/* h2d_vgamouse.h  Feb 18  12:3:31  1999 */
/* Generated by H2D v1.31.1 */
/* from module h2d_vgamouse and header vgamouse.h. */
/* Types which were created during translation */

#include <svgalib/vgamouse.h>

#ifndef h2d_vgamouse_H_
#define h2d_vgamouse_H_

#endif  /* h2d_vgamouse_H_ */