
#define MAIN_ICON	10

#define BMP_ABOUT	100
#define BMP_LOGO	101


#define IDSTR_SHELLNAME		20001
#define IDSTR_INIFILENAME	20002
#define IDSTR_XREDFILENAME	20003
#define IDSTR_HELPFILENAME	20004
#define IDSTR_IDEHELPFILENAME	20005

#define COMPILE			1
#define COMPILE_NOPROJ		2
#define MAKE			3
#define MAKE_NOPROJ		4
#define BUILD			5
#define BUILD_NOPROJ		6
#define MAKELIST		7
#define MAKELIST_NOPROJ		8
#define DEBUG			9

#define IDSTR_CMDLINE		20100
#define IDSTR_COMPILE_CMDLINE		IDSTR_CMDLINE + COMPILE
#define IDSTR_COMPILE_NOPROJ_CMDLINE	IDSTR_CMDLINE + COMPILE_NOPROJ
#define IDSTR_MAKE_CMDLINE		IDSTR_CMDLINE + MAKE
#define IDSTR_MAKE_NOPROJ_CMDLINE	IDSTR_CMDLINE + MAKE_NOPROJ
#define IDSTR_BUILD_CMDLINE		IDSTR_CMDLINE + BUILD
#define IDSTR_BUILD_NOPROJ_CMDLINE	IDSTR_CMDLINE + BUILD_NOPROJ
#define IDSTR_MAKELIST_CMDLINE		IDSTR_CMDLINE + MAKELIST
#define IDSTR_MAKELIST_NOPROJ_CMDLINE	IDSTR_CMDLINE + MAKELIST_NOPROJ
#define IDSTR_DEBUG_CMDLINE		IDSTR_CMDLINE + DEBUG

#define IDSTR_TITLE		20200
#define IDSTR_COMPILE_TITLE		IDSTR_TITLE + COMPILE
#define IDSTR_COMPILE_NOPROJ_TITLE	IDSTR_TITLE + COMPILE_NOPROJ
#define IDSTR_MAKE_TITLE		IDSTR_TITLE + MAKE
#define IDSTR_MAKE_NOPROJ_TITLE		IDSTR_TITLE + MAKE_NOPROJ
#define IDSTR_BUILD_TITLE		IDSTR_TITLE + BUILD
#define IDSTR_BUILD_NOPROJ_TITLE	IDSTR_TITLE + BUILD_NOPROJ
#define IDSTR_MAKELIST_TITLE		IDSTR_TITLE + MAKELIST
#define IDSTR_MAKELIST_NOPROJ_TITLE	IDSTR_TITLE + MAKELIST_NOPROJ
#define IDSTR_DEBUG_TITLE		IDSTR_TITLE + DEBUG

#define IDSTR_MENU		20300
#define IDSTR_COMPILE_MENU		IDSTR_MENU + COMPILE			
#define IDSTR_COMPILE_NOPROJ_MENU	IDSTR_MENU + COMPILE_NOPROJ		
#define IDSTR_MAKE_MENU			IDSTR_MENU + MAKE			
#define IDSTR_MAKE_NOPROJ_MENU		IDSTR_MENU + MAKE_NOPROJ		
#define IDSTR_BUILD_MENU		IDSTR_MENU + BUILD			
#define IDSTR_BUILD_NOPROJ_MENU		IDSTR_MENU + BUILD_NOPROJ		
#define IDSTR_MAKELIST_MENU             IDSTR_MENU + MAKELIST		
#define IDSTR_MAKELIST_NOPROJ_MENU	IDSTR_MENU + MAKELIST_NOPROJ		
#define IDSTR_DEBUG_MENU		IDSTR_MENU + DEBUG			

#define IDSTR_INV_MENU		20400
#define IDSTR_COMPILE_INV_MENU		IDSTR_INV_MENU + COMPILE			
#define IDSTR_COMPILE_NOPROJ_INV_MENU	IDSTR_INV_MENU + COMPILE_NOPROJ		
#define IDSTR_MAKE_INV_MENU		IDSTR_INV_MENU + MAKE			
#define IDSTR_MAKE_NOPROJ_INV_MENU	IDSTR_INV_MENU + MAKE_NOPROJ		
#define IDSTR_BUILD_INV_MENU		IDSTR_INV_MENU + BUILD			
#define IDSTR_BUILD_NOPROJ_INV_MENU	IDSTR_INV_MENU + BUILD_NOPROJ		
#define IDSTR_MAKELIST_INV_MENU		IDSTR_INV_MENU + MAKELIST		
#define IDSTR_MAKELIST_NOPROJ_INV_MENU	IDSTR_INV_MENU + MAKELIST_NOPROJ		
#define IDSTR_DEBUG_INV_MENU		IDSTR_INV_MENU + DEBUG			

#define IDSTR_HOTKEY		20500
#define IDSTR_COMPILE_HOTKEY		IDSTR_HOTKEY + COMPILE			
#define IDSTR_COMPILE_NOPROJ_HOTKEY	IDSTR_HOTKEY + COMPILE_NOPROJ		
#define IDSTR_MAKE_HOTKEY		IDSTR_HOTKEY + MAKE			
#define IDSTR_MAKE_NOPROJ_HOTKEY	IDSTR_HOTKEY + MAKE_NOPROJ		
#define IDSTR_BUILD_HOTKEY		IDSTR_HOTKEY + BUILD			
#define IDSTR_BUILD_NOPROJ_HOTKEY	IDSTR_HOTKEY + BUILD_NOPROJ		
#define IDSTR_MAKELIST_HOTKEY		IDSTR_HOTKEY + MAKELIST		
#define IDSTR_MAKELIST_NOPROJ_HOTKEY	IDSTR_HOTKEY + MAKELIST_NOPROJ		
#define IDSTR_DEBUG_HOTKEY		IDSTR_HOTKEY + DEBUG			

#define IDSTR_COMMENT		20600
#define IDSTR_COMPILE_COMMENT		IDSTR_COMMENT + COMPILE			
#define IDSTR_COMPILE_NOPROJ_COMMENT	IDSTR_COMMENT + COMPILE_NOPROJ		
#define IDSTR_MAKE_COMMENT		IDSTR_COMMENT + MAKE			
#define IDSTR_MAKE_NOPROJ_COMMENT	IDSTR_COMMENT + MAKE_NOPROJ		
#define IDSTR_BUILD_COMMENT		IDSTR_COMMENT + BUILD			
#define IDSTR_BUILD_NOPROJ_COMMENT	IDSTR_COMMENT + BUILD_NOPROJ		
#define IDSTR_MAKELIST_COMMENT		IDSTR_COMMENT + MAKELIST		
#define IDSTR_MAKELIST_NOPROJ_COMMENT	IDSTR_COMMENT + MAKELIST_NOPROJ		
#define IDSTR_DEBUG_COMMENT		IDSTR_COMMENT + DEBUG			

#define IDSTR_STARTDIR		20700
#define IDSTR_COMPILE_STARTDIR		IDSTR_STARTDIR + COMPILE	
#define IDSTR_COMPILE_NOPROJ_STARTDIR	IDSTR_STARTDIR + COMPILE_NOPROJ		
#define IDSTR_MAKE_STARTDIR		IDSTR_STARTDIR + MAKE			
#define IDSTR_MAKE_NOPROJ_STARTDIR	IDSTR_STARTDIR + MAKE_NOPROJ		
#define IDSTR_BUILD_STARTDIR		IDSTR_STARTDIR + BUILD			
#define IDSTR_BUILD_NOPROJ_STARTDIR	IDSTR_STARTDIR + BUILD_NOPROJ		
#define IDSTR_MAKELIST_STARTDIR		IDSTR_STARTDIR + MAKELIST		
#define IDSTR_MAKELIST_NOPROJ_STARTDIR	IDSTR_STARTDIR + MAKELIST_NOPROJ		
#define IDSTR_DEBUG_STARTDIR		IDSTR_STARTDIR + DEBUG			

#define IDSTR_DIRLIST		21000
#define IDSTR_DEFMAINMOD	21001
#define IDSTR_TEMPLATE		21002
#define IDSTR_STDREDFILE	21003
#define IDSTR_EXEFILE		21004
#define IDSTR_EXEFILE_NOPROJ	21005
#define IDSTR_RUNDIR		21006
#define IDSTR_RUNDIR_NOPROJ	21007
#define IDSTR_XC_EXTENSIONS	21008
#define IDSTR_XDSMAIN		20009

#define IDSTR_OPEN_FILTER	25000

#define IDSTR_SAMPLE_FILES	26000
#define IDSTR_SAMPLE_MESSAGES	27000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

